### ISSUE TITLE
Absence of "requirements.txt" file in the project

### ISSUE THREAD

**Issue by abhi7745** [Sahilopl/Socialgram-Django-App#10]
I noticed that the "requirements.txt" file is missing in the Django project. This file is essential for managing project dependencies. Please add it.

**Comment by ADITYAVOFFICIAL** [comment]
Thank you for bringing the issue to our attention. I'm pleased to inform you that we've successfully implemented the required changes, and I will now proceed to close this issue. Your diligence is greatly appreciated.
