### ISSUE TITLE
Missing Pillow Dependency in Requirements.txt file

### ISSUE THREAD

**Issue by abhi7745** [Sahilopl/Socialgram-Django-App#12]
Hai, I hope you're doing well. I wanted to bring to your attention an issue I encountered while trying to run the project. It seems to be related to a missing Pillow dependency in the project's requirements.txt file.

I checked the requirements.txt file, and it appears that Pillow is not listed as a required package. To resolve this issue, I suggest adding Pillow to the project's requirements.txt file. This will ensure that all users can easily install the necessary dependencies for the project to function correctly.

**Comment by ADITYAVOFFICIAL** [comment]
Hello,

Thank you for bringing this to our attention. We have added the Pillow dependency to the requirements.txt file as you suggested. This should resolve the issue you were facing.

We appreciate your contribution to improving our project. Your feedback helps us make the project better for everyone.
Happy Hacktoberfeset!

Best regards, 𝐀𝐃𝐈𝐓𝐘𝐀 𝐕𝐄𝐑𝐌𝐀
