### ISSUE TITLE
Common Nav bar

### ISSUE THREAD

**Issue by docjon09** [Sahilopl/Socialgram-Django-App#7]
Currently, there is no common nav bar in this website. So, if the user goes to see the profile of another person, there is no way to go back to main page without clicking back button. Making a common nav bar will also reduce repetitive code.

**Comment by docjon09** [comment]
Please assign this task to me as part of hacktoberfest.

**Comment by Sahilopl** [comment]
Okk

**Comment by Sahilopl** [comment]
yeah. Thanks for pointing it out. I will be keeping this issue open if you want to contribute to the above issue you can make a pull request with the necessary changes. Happy Hacktoberfest !

**Comment by ADITYAVOFFICIAL** [comment]
Good 👍

**Comment by ADITYAVOFFICIAL** [comment]
I'll be closing the issue as it's resolved. Repo merging in 5 minutes. Thanks for Hacktoberfest contributions! Feel free to create more issues. Good luck in your future contributions!
